### ISSUE TITLE
JS Comments 

### ISSUE THREAD

**Issue by Ari-Shatunovsky** [lanaleyla/Exercise6_promise#1]
1. Why to put promise inside promise. It shouldn't be like that. Your function should return one promise and then you should call this function and make then/catch on it.
2. Using flag is not necessary here. You can write it much simpler.
3. Use camelCase for function names.
4. You can use string templates instead of +.
5. Code in not aligned well.

**Comment by lanaleyla** [comment]
fixed the code according to the issues. thanks
